"""Add channel and message num to Post

Revision ID: a0ded367c1fb
Revises: e568daeeb580
Create Date: 2025-10-04 14:50:18.650497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ded367c1fb'
down_revision: Union[str, None] = 'e568daeeb580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__Channels__id'), 'Channels', ['id'])
    op.create_unique_constraint(op.f('uq__News__id'), 'News', ['id'])
    op.add_column('Posts', sa.Column('channel_id', sa.UUID(), nullable=False))
    op.add_column('Posts', sa.Column('message_num', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq__Posts__id'), 'Posts', ['id'])
    op.create_foreign_key(op.f('fk__Posts__channel_id__Channels'), 'Posts', 'Channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__Posts__channel_id__Channels'), 'Posts', type_='foreignkey')
    op.drop_constraint(op.f('uq__Posts__id'), 'Posts', type_='unique')
    op.drop_column('Posts', 'message_num')
    op.drop_column('Posts', 'channel_id')
    op.drop_constraint(op.f('uq__News__id'), 'News', type_='unique')
    op.drop_constraint(op.f('uq__Channels__id'), 'Channels', type_='unique')
    # ### end Alembic commands ###
