"""News model

Revision ID: a3030ea569c6
Revises: cdd7c8230db3
Create Date: 2025-10-04 17:53:56.392168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3030ea569c6'
down_revision: Union[str, None] = 'cdd7c8230db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Drafts')),
    sa.UniqueConstraint('id', name=op.f('uq__Drafts__id'))
    )
    op.create_table('Duplicates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('news_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.id'], name=op.f('fk__Duplicates__news_id__News')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Duplicates')),
    sa.UniqueConstraint('id', name=op.f('uq__Duplicates__id'))
    )
    op.create_index(op.f('ix__Duplicates__news_id'), 'Duplicates', ['news_id'], unique=False)
    op.create_table('Entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('news_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.id'], name=op.f('fk__Entities__news_id__News')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Entities')),
    sa.UniqueConstraint('id', name=op.f('uq__Entities__id'))
    )
    op.create_index(op.f('ix__Entities__news_id'), 'Entities', ['news_id'], unique=False)
    op.create_table('Sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('news_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.id'], name=op.f('fk__Sources__news_id__News')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Sources')),
    sa.UniqueConstraint('id', name=op.f('uq__Sources__id'))
    )
    op.create_index(op.f('ix__Sources__news_id'), 'Sources', ['news_id'], unique=False)
    op.create_table('Timelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('news_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['News.id'], name=op.f('fk__Timelines__news_id__News')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Timelines')),
    sa.UniqueConstraint('id', name=op.f('uq__Timelines__id'))
    )
    op.create_index(op.f('ix__Timelines__news_id'), 'Timelines', ['news_id'], unique=False)
    op.add_column('News', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('News', sa.Column('hotness', sa.Float(), nullable=True))
    op.add_column('News', sa.Column('sentiment', sa.Integer(), nullable=True))
    op.add_column('News', sa.Column('why_now', sa.String(), nullable=True))
    op.drop_column('News', 'text')
    op.drop_column('News', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('News', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('News', 'why_now')
    op.drop_column('News', 'sentiment')
    op.drop_column('News', 'hotness')
    op.drop_column('News', 'headline')
    op.drop_index(op.f('ix__Timelines__news_id'), table_name='Timelines')
    op.drop_table('Timelines')
    op.drop_index(op.f('ix__Sources__news_id'), table_name='Sources')
    op.drop_table('Sources')
    op.drop_index(op.f('ix__Entities__news_id'), table_name='Entities')
    op.drop_table('Entities')
    op.drop_index(op.f('ix__Duplicates__news_id'), table_name='Duplicates')
    op.drop_table('Duplicates')
    op.drop_table('Drafts')
    # ### end Alembic commands ###
