"""Remove old from user

Revision ID: d9a0eb58166b
Revises: cff61c3f21cd
Create Date: 2025-10-03 21:43:24.197585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a0eb58166b'
down_revision: Union[str, None] = 'cff61c3f21cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Users')),
    sa.UniqueConstraint('email', name=op.f('uq__Users__email')),
    sa.UniqueConstraint('id', name=op.f('uq__Users__id'))
    )
    op.create_index(op.f('ix__Users__username'), 'Users', ['username'], unique=True)
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hobby', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix__Users__username'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
