"""Add News, Post, Channel models

Revision ID: e568daeeb580
Revises: d9a0eb58166b
Create Date: 2025-10-04 01:43:32.013452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e568daeeb580'
down_revision: Union[str, None] = 'd9a0eb58166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('last_message_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Channels')),
    sa.UniqueConstraint('id', name=op.f('uq__Channels__id'))
    )
    op.create_table('News',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__News')),
    sa.UniqueConstraint('id', name=op.f('uq__News__id'))
    )
    op.create_table('Posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Posts')),
    sa.UniqueConstraint('id', name=op.f('uq__Posts__id'))
    )
    op.create_unique_constraint(op.f('uq__Users__id'), 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Users__id'), 'Users', type_='unique')
    op.drop_table('Posts')
    op.drop_table('News')
    op.drop_table('Channels')
    # ### end Alembic commands ###
